# Generated by Django 5.0.4 on 2024-05-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_birth_date_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='creator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
